baseUrl: https://example.com
title: Slick Temple
theme: slick_temple

metaDataFormat: yaml

# If set, it will appear below the footer links
copyright: (c) 2018 Some Author — All rights reserved.

params:
    # Enables syntax highlighting
    highlight: true
    # Supports highlighting for languages not included in the original pack
    # See https://highlightjs.org/download/ for what's included in original pack
    # For reference to all languages, see:
    # https://github.com/isagalaev/highlight.js/tree/master/src/languages
    hjslangs:
    - go
    - vim
    # Enables the topmenu, which pulls from categories
    topmenu: categories

    # Enables custom date format (optional, the default is MM-DD-YYYY)
    # For reference to date and time templating, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateformatpretty: Mon, 02 Jan 2006 15:04:05 MST

# Builds a list page for each category given
taxonomies:
  category: categories
  tag: tags

author:
  name: Some Author
  email: some@email.com
  gaid: Your Google Analytics ID
  github: github
  twitter: twitterID
  medium: mediumUsername
