name = "Slick Temple"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
description = "A Hugo theme focused on content, cleanliness, speed, responsiveness and privacy"
homepage = "https://github.com/spookey/slick_temple"
tags = ["blog", "personal", "responsive", "minimal"]
features = ["highlightjs", "responsive", "black-and-white"]
min_version = 0.13

[author]
    name = "Frieder Grießhammer"
    homepage = "https://www.der-beweis.de"

[original]
    name = "Temple"
    homepage = "http://aos.github.io"
    repo = "https://github.com/aos/temple"
