name = "Slick Temple"
description = "Minimal hugo theme with focus on content and speed"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
homepage = "https://github.com/spookey/slick_temple"
tags = ["blog", "personal", "responsive", "minimal"]
features = ["highlightjs", "responsive", "black-and-white"]
min_version = 0.13

[author]
    name = "Frieder Grießhammer"
    homepage = "https://www.der-beweis.de"
