# Set base URL for site - must end with a trailing slash
baseUrl = "/"

title = "Slick Temple"
theme = "slick_temple"

languageCode = "en"

# Will appear below the footer links with a © sign and the current year
copyright = "Some Author — All rights reserved."

[params]
    # Site description
    description = "Example site for Slick Temple Hugo theme"

    # Favicon file (relative to baseURL)
    favicon = "img/favicon.png"

    # Enables the topmenu, which pulls from categories
    topmenu = "categories"

    # Enables custom date format (optional, the default is MM-DD-YYYY)
    # For reference to date and time templating, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    datefmt = "Mon, 02 Jan 2006 15:04:05 MST"

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


[author]
    name = "Some Author"
    email = "some@email.com"

[[menu.footer]]
name = "GitHub"
url = "https://github.com/someauthor"
weight = 1

[[menu.footer]]
name = "Medium"
url = "https://medium.com/@someauthor"
weight = 3

[[menu.footer]]
name = "Twitter"
url = "https://twitter.com/someauthor"
weight = 2
